# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowcontract",
            name="delivery_qr_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="escrowcontract",
            name="payment_link",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="escrowcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("FUNDED", "Funded"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED_UNVERIFIED", "Delivered (Unverified)"),
                    ("COMPLETED", "Completed"),
                    ("DISPUTED", "Disputed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING_PAYMENT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("RESOLVED_REFUNDED", "Resolved - Refunded"),
                    ("RESOLVED_RELEASED", "Resolved - Released"),
                ],
                db_index=True,
                default="OPEN",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="INITIATED",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="escrow_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ledger_entry_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="payout_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("account_type",),
                name="uniq_system_ledger_account",
            ),
        ),
    ]
