# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ledger_immutability"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="escrowcontract",
            constraint=models.CheckConstraint(
                condition=~models.Q(("buyer", models.F("seller"))),
                name="escrow_buyer_ne_seller",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgertransaction",
            constraint=models.UniqueConstraint(
                fields=("escrow_contract", "transaction_type"),
                name="uniq_ledger_txn_per_escrow_type",
            ),
        ),
    ]
